// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CunningFlyersResources
{
        public const string achievement_first_point = "CgkIqLaR3I0QEAIQAQ"; // <GPGSID>
        public const string achievement_5_points = "CgkIqLaR3I0QEAIQAg"; // <GPGSID>
        public const string achievement_100_points = "CgkIqLaR3I0QEAIQCA"; // <GPGSID>
        public const string achievement_200_points = "CgkIqLaR3I0QEAIQCg"; // <GPGSID>
        public const string leaderboard_global_scoreboard = "CgkIqLaR3I0QEAIQBg"; // <GPGSID>
        public const string achievement_30_points = "CgkIqLaR3I0QEAIQBQ"; // <GPGSID>
        public const string achievement_20_points = "CgkIqLaR3I0QEAIQBA"; // <GPGSID>
        public const string achievement_10_points = "CgkIqLaR3I0QEAIQAw"; // <GPGSID>
        public const string achievement_150_points = "CgkIqLaR3I0QEAIQCQ"; // <GPGSID>
        public const string achievement_50_points = "CgkIqLaR3I0QEAIQBw"; // <GPGSID>

}

